# Generated by Django 5.0.2 on 2024-04-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='Categoria',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
